### ISSUE TITLE
Python error for send_command

### ISSUE THREAD

**Issue by lukas-kd** [Mattes83/nymea#2]
Hello,
i am using this integration and facing the following issue, while updating the entity states:

Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state await self.async_device_update() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update await hass.async_add_executor_job(self.update) File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/nymea/cover.py", line 168, in update value = self._maveoStick.maveoBox.send_command( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable

Could you have a look at this?

Additional information:
After a HA restart it works for some time.
I also restart the maveo box every second night.

Thanks. :)

**Comment by tomu1907** [comment]
I can´t solve your problem, but I have a question regarding the restart of the box.
How do you do that? Manually or automatically? I´m still looking for a solution to do that automatically.

**Comment by lukas-kd** [comment]
I am using a shelly plug s, which will turn off, wait 10 seconds and then turn it back on.

Triggerd by an automation from home assistant.

**Comment by minhkhoiii1997** [comment]
Hi, I have a question, I tried to install this integration using HACS and click on Custom Repository and pasted in this link https://github.com/Mattes83/nymea. I got the error saying that "Repository structure for main is not compliant".

I'm still new to Home Assistant so any suggestions would help. Thank you!

**Comment by Mattes83** [comment]
> Hi, I have a question, I tried to install this integration using HACS and click on Custom Repository and pasted in this link https://github.com/Mattes83/nymea. I got the error saying that "Repository structure for main is not compliant".
> 
> 
> 
> I'm still new to Home Assistant so any suggestions would help. Thank you!

You need to copy the content of this repo onto the custom_components folder in home assistant. I will have a look at the required repo structure in the near future, this should be easy to adapt.

**Comment by Mattes83** [comment]
> Hello,
> i am using this integration and facing the following issue, while updating the entity states:
> 
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state await self.async_device_update() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update await hass.async_add_executor_job(self.update) File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/nymea/cover.py", line 168, in update value = self._maveoStick.maveoBox.send_command( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable
> 
> Could you have a look at this?
> 
> Additional information:
> After a HA restart it works for some time.
> I also restart the maveo box every second night.
> 
> Thanks. :)
> 

I guess i need to improve the error handling. It looks like some connection failure. I'll have a look at it. 

Just out of curiosity: why do you need to restart it regularly?

**Comment by minhkhoiii1997** [comment]
Hi @Mattes83, where can I find the custom_components folder in home assistant? Would it be under HACS? Sorry, I'm new to HA, so any suggestions help!

**Comment by Mattes83** [comment]
> Hi, I have a question, I tried to install this integration using HACS and click on Custom Repository and pasted in this link https://github.com/Mattes83/nymea. I got the error saying that "Repository structure for main is not compliant".
> 
> I'm still new to Home Assistant so any suggestions would help. Thank you!

Please try it again. I added a hacs.json file to make it work

**Comment by Mattes83** [comment]
> Hello, i am using this integration and facing the following issue, while updating the entity states:
> 
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state await self.async_device_update() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update await hass.async_add_executor_job(self.update) File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/nymea/cover.py", line 168, in update value = self._maveoStick.maveoBox.send_command( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable
> 
> Could you have a look at this?
> 
> Additional information: After a HA restart it works for some time. I also restart the maveo box every second night.
> 
> Thanks. :)

I just pushed the version I am using at the moment.
If it happens with this new version I'd be happy if you provide the new error log, I'll then try to fix it

**Comment by lukas-kd** [comment]
> > > Hi, I have a question, I tried to install this integration using HACS and click on Custom Repository and pasted in this link https://github.com/Mattes83/nymea. I got the error saying that "Repository structure for main is not compliant".
> > > I'm still new to Home Assistant so any suggestions would help. Thank you!
> > 
> > 
> > Please try it again. I added a hacs.json file to make it work
> 
> Thank you for this! Also, it asks for IP address and Port, I was looking at this post here from Tomu https://community.home-assistant.io/t/maveo-garage-door-integration/278761, he said to enable TCP, but there is no option for me on Maveo app iOS device for some reason. I tried to search for this, but I couldn't find it. My device is BlueFi Stick version 1.11.14

You dont need to open a tcp port, because it uses the nymea port and not a 3rd party port.

**Comment by lukas-kd** [comment]
> > Hello,
> > i am using this integration and facing the following issue, while updating the entity states:
> > Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state await self.async_device_update() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update await hass.async_add_executor_job(self.update) File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/nymea/cover.py", line 168, in update value = self._maveoStick.maveoBox.send_command( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable
> > Could you have a look at this?
> > Additional information:
> > After a HA restart it works for some time.
> > I also restart the maveo box every second night.
> > Thanks. :)
> 
> I guess i need to improve the error handling. It looks like some connection failure. I'll have a look at it.
> 
> Just out of curiosity: why do you need to restart it regularly?

Because sometimes one of my two garages loses its connection, with a restart it works as expected for the next 3-5 days.
But with this integration it only works like 1 hour or two, but the app works with no problem and shows the symbol for a successfull connection.

So i dont exactly know, whats here the problem. But it looks like it will set any object (maveoStick or maveoBox) to None if a failure occurs.
Would be nice to get this integrated with the is_available or something like this, with reconnection maybe?
I dont know the code of the integration if anything is there already implemented.

I will install the hacs version (instead of the current copy / paste variant) to get the update notifications. Thanks for that! :)

**Comment by minhkhoiii1997** [comment]
> > > > Hi, I have a question, I tried to install this integration using HACS and click on Custom Repository and pasted in this link https://github.com/Mattes83/nymea. I got the error saying that "Repository structure for main is not compliant".
> > > > I'm still new to Home Assistant so any suggestions would help. Thank you!
> > > 
> > > 
> > > Please try it again. I added a hacs.json file to make it work
> > 
> > 
> > Thank you for this! Also, it asks for IP address and Port, I was looking at this post here from Tomu https://community.home-assistant.io/t/maveo-garage-door-integration/278761, he said to enable TCP, but there is no option for me on Maveo app iOS device for some reason. I tried to search for this, but I couldn't find it. My device is BlueFi Stick version 1.11.14
> 
> You dont need to open a tcp port, because it uses the nymea port and not a 3rd party port.

Hello,

So what port should I be using? It's a required field and I cannot leave it blank. The default value that you put there is 2223. And when I put in the IP address, it said failed to connect.

**Comment by Mattes83** [comment]
this is the default port on the maveo box. have you chosen the right ip? you can check on your router. you should also make sure the box always gets the same ip. another way is to check via the nymea app. maveo box is running nymea with some custom addons.

**Comment by lukas-kd** [comment]
Any updates about the error?
I am losing the connection within 5 minutes... app works.

**Comment by Mattes83** [comment]
I am currently testing  a new version which might be a bit more fault tolerant. I'll make a release if it works out for me.

**Comment by nicolinuxfr** [comment]
I'm not sure if it's the same error, I see nothing in the Home Assistant log. But when I try to add the stick, I have an instant error, as if it did not even tried to connect : 
<img width="437" alt="Capture d’écran 2024-09-12 à 14 12 16" src="https://github.com/user-attachments/assets/b4bef16b-9807-42aa-93e4-22b12ce252cc">

One weird thing I noticed : after each error, the IP adress changes to the one displayed in the screenshot above. It's not the correct one, but it seems the plugin wants to use it every time.

Let me know if I can help you debug all this.

Thanks for your work. 🙂

**Comment by Mattes83** [comment]
@nicolinuxfrtldr: there is no endpoint at the up/port combination you provided. I think this is unrelated. When you confirm the dialog the component checks if there is an endpoint at the ip/port combination you provided. if it can’t reach anything you get this error message. the dialog data seems to be filled with default data afterwards. that might be annoying but should be no problem.

**Comment by nicolinuxfr** [comment]
@Mattes83 OK so why is there no endpoint ? The IP address is correct and the device works from the Maveo app. What should I try ?

**Comment by Mattes83** [comment]
there is a nymea app with which you can access your box and configure ports. this can be misconfigured somehow or you have them in separate lans, firewall issues….there are endless possibilities that you need to find out yourself i guess. you can also try telnet from the machine you are running home assistant on

**Comment by lukas-kd** [comment]
> @Mattes83 OK so why is there no endpoint ? The IP address is correct and the device works from the Maveo app. What should I try ?

You could run nmap against your device to find the open ports.
You could even get the filtered state, if this port is blocked.

**Comment by nicolinuxfr** [comment]
Thanks @Mattes83 and @lukas-kd for your suggestions. Initial testings seem to indicate I have zero port open on this IP address, which is weird.

As for the Nymea app, it seems to need installing a whole server using a Raspberry Pi or something else. Maybe I misunderstood something, but the Maveo Stick should be enough, right ?

**Comment by lukas-kd** [comment]
No, you need the hub for this. The stick (in my case) was only for connecting the devices. But it should not have any ip..
The gateway has one.

**Comment by nicolinuxfr** [comment]
@lukas-kd Oh, I was not aware of that ! So you installed the nymea project alongside Home Assistant ?

I'm currently tying using this project https://github.com/nymea/nymea-docker but I'm going nowhere, I have a permission error pulling things when trying to build.

**Comment by lukas-kd** [comment]
> @lukas-kd Oh, I was not aware of that ! So you installed the nymea project alongside Home Assistant ?
> 
> EDIT : nevermind, I'm currently installing it. Thanks !

I have a maveo box (which runs nymea internally). And the ip of this box is the correct adress.

**Comment by nicolinuxfr** [comment]
OK, I'm thinking about returning the product then, I can't manage to install nymea on my Mini-PC where Home Assistant and everything else is already installed and I really don't want to have a second device dedicated to this.

But now I understand why this project won't work. Maybe adding this requirement to the Readme would help ? I thought the maveo stick was enough.

**Comment by nicolinuxfr** [comment]
Sorry if we go out of the scope of the plugin, but I would like to be sure : I installed the nymea:core on a Raspberry Pi and it works for the nymea:app, but there is apparently no way to add my garage door. I find no Maveo or Marantec option, and the generic garage door offered in the app does nothing.

Don't you think I need the Maveo box and nothing else ? I have a feeling they are using the Nymea system internally, but I can't use their stick alone from a different Nymea:core setup.

Am I missing something here ?

Thanks again 🙂

**Comment by Mattes83** [comment]
does your nymea show the maveo plugin under settings-> plugins? the pi also needs to be in bluetooth range to the stick

**Comment by nicolinuxfr** [comment]
@Mattes83 no, there is no Maveo plugin anywhere. I’m not sure what’s going on, but the Maveo box is also nowhere to be found. It’s really a weird product right now.

**Comment by Mattes83** [comment]
The maveo box is a nymea core installation with custom plugins. without the
plugins it won‘t work.

I do not think the product is weird. think of the box as a hub and the
stick and sensors as accessories.

Nicolas Furno ***@***.***> schrieb am So. 15. Sept. 2024 um
20:45:

**Comment by nicolinuxfr** [comment]
>  think of the box as a hub and the stick and sensors as accessories.

Well OK, but I can't order the box. 🤷‍♂️

Anyway, sorry to disturb this issue with my problems, I will return the Maveo Stick and go with the cheap garage openers (Meross like) route. 🙂

**Comment by Mattes83** [comment]
@lukas-kd Do you still have issues? I uploaded a new version some days ago.

**Comment by lukas-kd** [comment]
> @lukas-kd Do you still have issues? I uploaded a new version some days ago.

I wanted to wait, but i've updated yesterday and it works till now, without any restart or something. So i think it shouöd be fixed.

Thank you very much :).

**Comment by lukas-kd** [comment]
We can close the issue, works well since thr change.

Only thing seems to be not working is, when restarting the maveo box. There seems to be no reconnect and i have to restart home assistant.

But i dont do this often, so it would only be a improvement for me.

Thanls. :)
